title: Woolcycle
author: photobill108
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  All about the bike and the ride.
# social links
twitter_username: manbikeveg # DO NOT include the @ character, or else the build will fail!
github_username:  photobill108
show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
